version: '3.0'
services:
  rasa:
    image: rasa/1.10.2-spacy-en
    ports:
      - 80:5005
    networks: 
      - app_net
    volumes:
      - ./:/app
    command:
      run 
      --enable-api
      --cors *
    
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    expose: 
      - 5055
    networks: 
      - app_net

networks: 
  app_net:
